// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0XdgCYU1VsqH_nuGHPCk7rgK2oXAPsT4',
    appId: '1:229269742044:web:442a5f9d4bde5af868ef19',
    messagingSenderId: '229269742044',
    projectId: 'nktlm-9dcfd',
    authDomain: 'nktlm-9dcfd.firebaseapp.com',
    storageBucket: 'nktlm-9dcfd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxrNWqpoAPqnkETv2WS7rR7OQuF48I4Q',
    appId: '1:229269742044:android:cbc9bcad8ba9f78d68ef19',
    messagingSenderId: '229269742044',
    projectId: 'nktlm-9dcfd',
    storageBucket: 'nktlm-9dcfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcGvGa7Lw--T8y5G_iMuxx2tZe-_Oo4ao',
    appId: '1:229269742044:ios:59a36d1184d107fc68ef19',
    messagingSenderId: '229269742044',
    projectId: 'nktlm-9dcfd',
    storageBucket: 'nktlm-9dcfd.appspot.com',
    iosBundleId: 'com.example.firstScrapping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcGvGa7Lw--T8y5G_iMuxx2tZe-_Oo4ao',
    appId: '1:229269742044:ios:abc5ec8bbdf468b268ef19',
    messagingSenderId: '229269742044',
    projectId: 'nktlm-9dcfd',
    storageBucket: 'nktlm-9dcfd.appspot.com',
    iosBundleId: 'com.example.firstScrapping.RunnerTests',
  );
}
